import base64
import datetime
import fcntl
import json
import os
import shlex
import shutil
import stat

from .constants import LOCK_FILE
from .policy import vmid_access, vmid_allowed
from .rules import expand_port_rules, get_vm_conf, get_vm_ip, get_vm_all_ips
from .utils import audit, run_cmd


def ensure_hook_script(conf):
    behavior = conf.get("settings", {}).get("behavior", {})
    script_path = str(behavior.get("hook_script_path", "/var/lib/vz/snippets/hook.py"))
    config_path = str(behavior.get("hook_config_path", "/etc/pve/vmnat_config.json"))
    cli_path = str(behavior.get("hook_cli_path", "/usr/local/bin/vmmgrctl.py"))

    os.makedirs(os.path.dirname(script_path), exist_ok=True)
    content = (
        "#!/usr/bin/env python3\n"
        "# Auto-generated by PVE-Manager\n"
        "import os\n"
        "import subprocess\n"
        "import sys\n\n"
        "if len(sys.argv) >= 3:\n"
        "    vmid = sys.argv[1]\n"
        "    phase = sys.argv[2]\n"
        f"    cli = os.environ.get('VMMGR_HOOK_CLI', '{cli_path}')\n"
        f"    cfg = os.environ.get('VMMGR_HOOK_CONFIG', '{config_path}')\n"
        "    subprocess.run([cli, '--config', cfg, 'hook', '--vmid', vmid, '--phase', phase], check=False)\n"
    )

    with open(script_path, "w", encoding="utf-8") as f:
        f.write(content)

    st = os.stat(script_path)
    os.chmod(script_path, st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return script_path


def handle_hook_event(vmid, phase, conf):
    phase = str(phase or "").strip().lower()
    if phase in ["post-start", "started", "start"]:
        apply_nat(vmid, "add", conf, explicit=False, batch=False)
        inject_policy_routing(vmid, conf)
        return "start-sync"
    if phase in ["pre-stop", "post-stop", "stopped", "stop"]:
        apply_nat(vmid, "del", conf, explicit=False, batch=False)
        return "stop-clean"
    return "ignored"


def cfg_cmd(conf, name, default):
    return str(conf.get("settings", {}).get("commands", {}).get(name, default))


def _delete_nat_rules(iptables_cmd, iptables_save_cmd, marker):
    snapshot = run_cmd([iptables_save_cmd, "-t", "nat"])
    if snapshot.returncode != 0:
        return

    for line in (snapshot.stdout or "").splitlines():
        if not line.startswith("-A ") or marker not in line:
            continue
        spec = line[3:].strip()
        tokens = shlex.split(spec)
        if not tokens:
            continue
        run_cmd([iptables_cmd, "-t", "nat", "-D"] + tokens)


def get_all_vms(conf, include_templates=False):
    pvesh = cfg_cmd(conf, "pvesh", "pvesh")
    raw = run_cmd([pvesh, "get", "/cluster/resources", "--type", "vm", "--output-format", "json"]).stdout
    try:
        items = json.loads(raw or "[]")
    except Exception:
        items = []
    if include_templates:
        return items
    return [v for v in items if int(v.get("template", 0)) == 0]




def parse_vms_str(input_str, conf, operation="general"):
    include_templates = str(operation).lower() == "hook"
    all_vms = {int(v["vmid"]): v for v in get_all_vms(conf, include_templates=include_templates)}
    result = set()

    for token in (input_str or "").split(","):
        token = token.strip().lower()
        if not token:
            continue

        if token == "all":
            for vmid in sorted(all_vms.keys()):
                if vmid_allowed(vmid, conf, operation=operation, explicit=False, batch=True):
                    result.add(vmid)
            continue

        if "-" in token:
            try:
                s, e = map(int, token.split("-", 1))
                for vmid in range(s, e + 1):
                    if vmid in all_vms and vmid_allowed(vmid, conf, operation=operation, explicit=False, batch=True):
                        result.add(vmid)
            except Exception:
                pass
            continue

        if token.isdigit():
            vmid = int(token)
            if vmid in all_vms and vmid_allowed(vmid, conf, operation=operation, explicit=True, batch=False):
                result.add(vmid)

    return " ".join(map(str, sorted(result)))


def apply_nat(vmid, action, conf, explicit=True, batch=False):
    vmid_str = str(vmid)
    access = vmid_access(vmid_str, conf, operation="nat", explicit=explicit, batch=batch)
    if not access["allow"]:
        return access["reason"]

    vm_conf = get_vm_conf(conf, vmid_str)
    target_ip = get_vm_ip(vmid_str, conf, scope="biz")
    if target_ip == "None":
        return "no-ip"

    iptables = cfg_cmd(conf, "iptables", "iptables")
    iptables_save = cfg_cmd(conf, "iptables_save", "iptables-save")

    tag = f"PVENAT-{vmid_str}"
    with open(LOCK_FILE, "w", encoding="utf-8") as lockfile:
        try:
            fcntl.flock(lockfile, fcntl.LOCK_EX)
            _delete_nat_rules(iptables, iptables_save, tag)
            if action == "del":
                return "deleted"

            if vm_conf.get("skip_pve_nat") or vm_conf.get("gateway_proxy"):
                return "bypassed"

            try:
                expanded_rules = expand_port_rules(vmid_str, conf, vm_conf)
            except ValueError:
                return "conflict-error"

            use_snat = vm_conf.get("use_snat") or conf.get("settings", {}).get("behavior", {}).get("default_use_snat", False)

            for _name, ext_p, int_p, proto in expanded_rules:
                # DNAT rule
                run_cmd(
                    [
                        iptables,
                        "-t",
                        "nat",
                        "-A",
                        "PREROUTING",
                        "-p",
                        str(proto),
                        "--dport",
                        str(ext_p),
                        "-m",
                        "comment",
                        "--comment",
                        tag,
                        "-j",
                        "DNAT",
                        "--to-destination",
                        f"{target_ip}:{int_p}",
                    ]
                )
                # Optional SNAT rule to handle asymmetric routing if policy routing is not used/desired
                if use_snat:
                    run_cmd(
                        [
                            iptables,
                            "-t",
                            "nat",
                            "-A",
                            "POSTROUTING",
                            "-p",
                            str(proto),
                            "-d",
                            str(target_ip),
                            "--dport",
                            str(int_p),
                            "-m",
                            "comment",
                            "--comment",
                            tag,
                            "-j",
                            "MASQUERADE",
                        ]
                    )
        finally:
            fcntl.flock(lockfile, fcntl.LOCK_UN)
    return "ok"


def inject_policy_routing(vmid, conf):
    vmid_str = str(vmid)
    vm_conf = get_vm_conf(conf, vmid_str)

    if not vm_conf.get("policy_routing", True):
        return "disabled"

    biz_ip = get_vm_ip(vmid_str, conf, scope="biz")
    if biz_ip == "None":
        return "no-biz-ip"

    # PVE internal IP on the same VLAN (defaulting to .226 as per user topology)
    pve_ip = conf.get("settings", {}).get("interfaces", {}).get("biz_pve_ip", "100.112.247.226")

    qm = cfg_cmd(conf, "qm", "qm")

    # Use a high priority table for our custom routing
    # We first try to delete the rule/route to avoid duplicates, then add
    commands = [
        f"ip rule del from {biz_ip} table 100",
        f"ip rule add from {biz_ip} table 100",
        f"ip route add default via {pve_ip} table 100",
    ]

    results = []
    for cmd in commands:
        # We don't check return code for 'del' because it might fail if not exists
        run = run_cmd([qm, "guest", "exec", vmid_str, "--"] + shlex.split(cmd))
        results.append(run.returncode == 0)

    audit(f"Policy routing injected for VM {vmid_str} (IP: {biz_ip}, GW: {pve_ip})")
    return "ok"


def audit_vm_network(vmid, conf):
    vmid_str = str(vmid)
    expected_ips = get_vm_all_ips(vmid_str, conf)
    if not expected_ips:
        return {"status": "no-config", "mismatches": []}

    qm = cfg_cmd(conf, "qm", "qm")
    # Command to get IPs in JSON format
    res = run_cmd([qm, "guest", "exec", vmid_str, "--", "ip", "-j", "addr"])

    actual_ips = []
    if res.returncode != 0:
        return {"status": "agent-error", "mismatches": []}

    try:
        data = json.loads(res.stdout or "{}")
        out_raw = ""
        if isinstance(data, dict) and "out-data" in data:
            out_raw = base64.b64decode(data["out-data"]).decode("utf-8")
        else:
            out_raw = res.stdout or ""

        # Parse the 'ip -j addr' output
        ip_data = json.loads(out_raw)
        for iface in ip_data:
            for addr in iface.get("addr_info", []):
                loc = addr.get("local")
                if loc:
                    actual_ips.append(str(loc))
    except Exception:
        # Fallback for older PVE versions or different output formats
        try:
            ip_data = json.loads(res.stdout or "[]")
            for iface in ip_data:
                for addr in iface.get("addr_info", []):
                    loc = addr.get("local")
                    if loc:
                        actual_ips.append(str(loc))
        except Exception:
            return {"status": "parse-error", "mismatches": []}

    mismatches = []
    for scope, exp_ip in expected_ips.items():
        if exp_ip not in actual_ips:
            mismatches.append({"scope": scope, "expected": exp_ip})

    return {
        "status": "ok" if not mismatches else "mismatch",
        "actual_ips": actual_ips,
        "mismatches": mismatches
    }


def sync_all(sync_type, full_reset, conf):
    iface_ext = conf.get("settings", {}).get("interfaces", {}).get("ext", "vmbr0")
    cidr = conf.get("settings", {}).get("behavior", {}).get("postrouting_cidr", "10.10.0.0/16")
    iptables = cfg_cmd(conf, "iptables", "iptables")
    iptables_save = cfg_cmd(conf, "iptables_save", "iptables-save")

    if full_reset:
        chk = run_cmd([iptables, "-t", "nat", "-C", "POSTROUTING", "-s", str(cidr), "-o", str(iface_ext), "-j", "MASQUERADE"])
        if chk.returncode != 0:
            run_cmd([iptables, "-t", "nat", "-A", "POSTROUTING", "-s", str(cidr), "-o", str(iface_ext), "-j", "MASQUERADE"])
        with open(LOCK_FILE, "w", encoding="utf-8") as lockfile:
            fcntl.flock(lockfile, fcntl.LOCK_EX)
            _delete_nat_rules(iptables, iptables_save, "PVENAT-")
            fcntl.flock(lockfile, fcntl.LOCK_UN)
        audit("Network full reset performed.")

    for vm in get_all_vms(conf):
        if vm.get("status") != "running":
            continue
        vmid = vm["vmid"]
        if sync_type in ["nat", "all"]:
            apply_nat(vmid, "add", conf, explicit=False, batch=True)


def power_action(vmid, act, conf):
    access = vmid_access(vmid, conf, operation="power", explicit=True, batch=False)
    if not access["allow"]:
        return False

    vms = {str(v["vmid"]): v["type"] for v in get_all_vms(conf)}
    if str(vmid) not in vms:
        return False

    qm = cfg_cmd(conf, "qm", "qm")
    pct = cfg_cmd(conf, "pct", "pct")
    run_cmd([pct if vms[str(vmid)] == "lxc" else qm, str(act), str(vmid)])
    audit(f"Power action {act} on VM {vmid}")
    return True


def backup_config(config_file, output_file=""):
    if not os.path.exists(config_file):
        raise FileNotFoundError(config_file)
    if not output_file:
        ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        output_file = f"{config_file}.bak.{ts}"
    shutil.copyfile(config_file, output_file)
    return output_file


